export const SET_EVENTS = 'SET_EVENTS';
export const SET_USER_LOCATION = 'SET_USER_LOCATION';
export const SET_SEARCH_BAR_VALUE = 'SET_SEARCH_BAR_VALUE';
export const TOGGLE_SEARCH_BAR = 'TOGGLE_SEARCH_BAR';
export const TOGGLE_LOADING = 'TOGGLE_LOADING';
